### ISSUE TITLE
Feedback técnico

### ISSUE THREAD

**Issue by Danielalab** [ZarelixCoder/lim-2018-05-bc-core-am-datadashboard#4]
El proyecto cumple con los requerimientos de funcionalidad y los tests cumplen con los porcentajes de cobertura.
- HTML : recuerda que tu html debe pasar el disguiete validador https://validator.w3.org/nu/?doc=https%3A%2F%2Fzarelixcoder.github.io%2Flim-2018-05-bc-core-am-datadashboard%2Fsrc%2F (ingresa al link para mayor detalle). También te recomendamos utilizar las etiquetas de html 5 semántico como section / form / main.
-  data.js : te recomendamos declarar el nombre de tus variables descriptivas, usando camel case y en inglés. Igualmente deberíás de declarar tus funciones antes de ejecutarlas (ver imagen)
![image](https://user-images.githubusercontent.com/32286663/42390104-7b337c68-8110-11e8-90f3-46f278da5666.png)
  También al hacer el uso de let y const , podrías declarar la siguiente variable(ver imagen) usando const ya que no le reasignas un nuevo valor.
![image](https://user-images.githubusercontent.com/32286663/42390150-a658d398-8110-11e8-8ceb-1f5d841d4000.png)
 Igualmente te recomendamos utilizar === (3) para evitar la conversión automática de javascript.
![image](https://user-images.githubusercontent.com/32286663/42390575-f717aa74-8111-11e8-9db0-2e3b47f1e417.png)

- index.js :  te recomendamos declarar el nombre de tus variables descriptivas, usando camel case y en inglés.  En el siguiente código (ver imagen) se repite por cada condición, podrías ejecutarlo al final de todas las condiciones. Te recomendamos también tener en cuenta que tu algoritmo debería funcionar par cualquier caso, en este caso podrías crear las urls de la data de manera dinámica.
![image](https://user-images.githubusercontent.com/32286663/42391064-a8b682b8-8113-11e8-83f8-51c0c0721447.png)

- css :  Te recomendamos el uso de clases en lugar de ids para dar los estilos ya que muestras estilos repetidos como margin 0 / heigth : 100 ; te recomendamos mantener una indentación de 2 espacios.
- Tests: el desarrollo de test cumple los porcentajes de cobertura y tus tests pasan sin ningún error, te recomendamos que para el desarrollo de los test utilices la data de fixtures  como el primer test de compute users Stats.
- Github : si bien utilizas los issues y milestones para dividir tus tareas, te recomendamos utilizarlos ya que tienes muchos issues que ya implementaste pero no has cerrado al igual que los milestones. 
- eslint (estilo) : 
![image](https://user-images.githubusercontent.com/32286663/42401674-6b0c6eea-813c-11e8-9fc7-e52eecdbbe26.png)

Buen trabajo sigue asi 👍

**Comment by ZarelaZanabria** [comment]
Gracias  @Danielalab  seguiré esforzándome para mejorar..!!
